- ignore:
    name: "Avoid lambda"
- ignore:
    name: "Use ||"
- ignore:
    name: "Reduce duplication"
    within:
      - "Data.GenValidity.Mergeful.Collection"
      - "Data.Mergeful.Collection.mergeSyncResponseIgnoreProblems"
- ignore:
    name: "Use const"
- ignore:
    name: "Redundant if"
    within:
      - "TestUtils.ClientDB"
- ignore:
    name: "Redundant do"
