resolver: lts-20.23
packages:
  - mergeful
  - genvalidity-mergeful
  - mergeful-persistent
  - mergeful-dirforest
  - genvalidity-mergeful-dirforest
extra-deps:
  - github: NorfairKing/dirforest
    commit: 4bca1e591afbb3697677ac0db84a585d9f13c0ec
    subdirs:
    - dirforest
    - genvalidity-dirforest
system-ghc: true
nix:
  enable: false
with-hpack: hpack
