resolver: lts-19.6
packages:
  - mergeful
  - genvalidity-mergeful
  - mergeful-persistent
extra-deps:
  - github: NorfairKing/autodocodec
    commit: a9b11fc5bba4c8de951eedf2b6308d6bec02dd0e
    subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

  - github: NorfairKing/safe-coloured-text
    commit: 675cb01fce5f46718416d7746de5b856ed90a63f
    subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

  - github: NorfairKing/sydtest
    commit: cf1bb414f0c0ce7bbf64659da94b8cd890c9e536
    subdirs:
    - sydtest
    - sydtest-discover

  - github: NorfairKing/validity
    commit: d88be911a7e2a84f6c089e9269aaed8d10a74acd
    subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector

nix:
  shell-file: shell.nix

