name:                genvalidity-mergeful
version:             0.0.0.0
github:              "NorfairKing/mergeful"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2019 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/NorfairKing/mergeful#readme>


library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - QuickCheck
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-time
    - mergeful

tests:
  mergeful-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - QuickCheck
      - containers
      - genvalidity-hspec
      - genvalidity-hspec-aeson
      - genvalidity-mergeful
      - genvalidity-typed-uuid
      - hspec
      - mergeful
      - mtl
      - pretty-show
      - random
      - time
      - typed-uuid
      - uuid
